[[constraint]]
  name = "github.com/cloudevents/sdk-go"
  version = "0.10.0"

[[constraint]]
  name = "github.com/google/uuid"
  version = "1.1.1"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.4.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[prune]
  go-tests = true
  unused-packages = true
