
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: sockeye
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: github.com/n3wscott/sockeye/cmd/sockeye
